### ISSUE TITLE
Changing the QIcon

### ISSUE THREAD

**Issue by kneeboarder** [tjmgis/PostGISSearch#5]
My colleague has the postgissearch_logo.png  QIcon(":/plugins/postgissearch/postgissearch_logo.png") with another image (same file name) but the new image doesn't show, the original image is still showing.

I can't figure out where it is getting the image from, is it caching it some where? help!!

Thanks

Steve

**Comment by tjmgis** [comment]
hi Steve

The icon is turned into the resources.py file so if that is still present
then it will always use the standard icon.

There is some info on this on this page:
http://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/plugins.html

Hope that helps

Tim
